name: Deploy Parking Finder

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  repository_dispatch:
    types: [data-update]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'parking-finder/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd parking-finder
        npm ci
        
    - name: Run linting
      run: |
        cd parking-finder
        npm run lint
        
    - name: Run unit tests
      run: |
        cd parking-finder
        npm run test:run
        
    - name: Run integration tests
      run: |
        cd parking-finder
        npm run test:integration
        
    - name: Run performance tests
      run: |
        cd parking-finder
        npm run test:performance
        
    - name: Install Playwright browsers
      run: |
        cd parking-finder
        npx playwright install --with-deps
        
    - name: Build application for E2E tests
      run: |
        cd parking-finder
        npm run build
        
    - name: Run E2E tests
      run: |
        cd parking-finder
        npm run test:e2e
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          parking-finder/test-results/
          parking-finder/playwright-report/
        retention-days: 30

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'parking-finder/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd parking-finder
        npm ci
        
    - name: Build application
      run: |
        cd parking-finder
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: parking-finder/dist

  deploy-github-pages:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  notify-deployment:
    if: always()
    runs-on: ubuntu-latest
    needs: [test, build, deploy-github-pages]
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.test.result }}" == "success" ] && [ "${{ needs.build.result }}" == "success" ] && [ "${{ needs.deploy-github-pages.result }}" == "success" ]; then
          echo "✅ All tests passed and deployment successful"
        else
          echo "❌ Tests failed or deployment failed"
          echo "Test result: ${{ needs.test.result }}"
          echo "Build result: ${{ needs.build.result }}"
          echo "Deploy result: ${{ needs.deploy-github-pages.result }}"
          exit 1
        fi